### PR TITLE
add indentation support for set tag

### PR DESCRIPTION
**Pull request by ahmetelgun**
# Pull Request Check List

- [] Added **tests** for changed code.
- [] Updated **documentation** for changed code.

I have a code like this. This code is not formatted very well. I tried to add support for `set` tag. I don't know how i write a test for this and i don't find a document section for this.

```
{% set schema=[
{
"name": "id",
"type": "integer",
"primary": true
},
{
"name": "name",
"type": "string"
}
] %}
```

Now, code formatted like this:

```
{% set schema=[
    {
        "name": "id",
        "type": "integer",
        "primary": true
    },
    {
        "name": "name",
        "type": "string"
    }
] %}
```

### CODE REVIEW

**Comment by christopherpickering** [comment]
Thanks for this, its a great start. I will see about adding tests.

**Comment by christopherpickering** [comment]
@ahmetelgun I expanded this a bit more - it will now also try to clean up the value of set. I added json5 library to parse javascript style json (single or no quotes on keys and values).

> if it is json then the json will be formatted w/ python's json.dump. With this we can indent the json if the line becomes too long.

> if the value is a list of tuples we can can use python eval to cleanup whitepsace and quotes... no line length formatting tho
some fancy logic could be added for that one day

> otherwise it will leave the formatting as-is... for example, if the json is invalid etc.

I added tests in the nunjucks > test_set folder.

Thanks a bunch for this!

closes #287 
closes #518
fixes 1/2 of #370 (still no function formatting)

json keys that don't require quoting in javascript will not be quoted here. Does that work in your case as well?

**Comment by christopherpickering** [comment]
looks like I accendently snuck in another change here that fixes some html tags getting formatted inside script tags.

**Comment by ahmetelgun** [comment]
Thanks for your help. I can't wait to use it 😃

**Pull request merged**
