### PR TITLE
Update H033 regex to ignore data-action

### PR DESCRIPTION
**Pull request by Mouarius**
# Pull Request Check List

Resolves: #issue-number-here

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

## Description of the context
I came across a linting issue when using djlint along with [Catalyst](https://catalyst.rocks/) custom elements : I was using the `data-action` attribute on a form element with multiline content, as it is defined in the [docs](https://catalyst.rocks/guide/actions/) for multiple actions.

Code example :
```html
<form action="#"
    method="get"
    data-action="
        submit:my-custom-element#handleFormSubmit
        click:my-custom-element#handleClick
        some-event:my-custom-element#handleSomething" >
    <!-- some content -->
</form>
```
## Error
I got a linting `H033 : Extra whitespace found in form action.` error, not for the `action` but for the `data-action`. I want it to apply only to `action` attributes.

## Reasons to fix it
I want to be able to have my actions string spanning over multiple lines without triggering an error with djlint, which maybe should not apply to a `data-action` attribute.
This is maybe a minor change, and I'm not an expert of regex so maybe someone should review my regex and the legitimity of my proposition.

What do you guys think ?

### CODE REVIEW

**Comment by silverwind** [comment]
Does not seem right. It should exactly match the `action` attribute and nothing else.

**Comment by Mouarius** [comment]
Apparently it doesn't, it triggered this rule with my `data-action` attribute on my form. As an example, I've tested this regex and apparently it does match everything containing "action" in it : https://regex101.com/r/8YN0EZ/1
Maybe I could change it to be sure that it only matches "action" exactly.

**Comment by silverwind** [comment]
Your latest version seems good, but I think it can be simpler and just look for a whitespace before `action`, so it does not need a lookbehind:

https://regex101.com/r/3ZAco0/2

**Comment by Mouarius** [comment]
You're right ! I'm changing it right now ! Thank you !

> Your latest version seems good, but I think it can be simpler and just look for a whitespace before `action`, so it does not need a lookbehind:
> 
> https://regex101.com/r/3ZAco0/2

You're right ! I'm changing it right now ! Thank you !

**Comment by silverwind** [comment]
Updated one more time, removed the unnecessary character class:

https://regex101.com/r/3ZAco0/3

**Comment by Mouarius** [comment]
I did it already ;)

**Comment by christopherpickering** [comment]
Thanks for this, sorry I missed it! I will update the pr with a test and release.

**Pull request merged**
