### PR TITLE
Defining custom blocks isn't strict enough

### PR DESCRIPTION
**Pull request by jafacakes2011**
# The issue?

If you define a custom block of `new_thing` but have a tag in your code `{% new_thing_2 %}` the current code will apply the custom blocks logic to `new_thing_2` even though it's not specified in the `custom_blocks` setting.

# The fix?

Adding a negative lookahead to the tags in the regex so that it only matches EXACT matches.

# Pull Request Check List

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code. (not needed?)

### CODE REVIEW

**Comment by christopherpickering** [comment]
Thanks for the fix!

What do we gain with negative lookahead?

It seems as though just \b will pass your tests?

image

image

> using \b https://regex101.com/r/GVh4HM/1
> using neg+\b https://regex101.com/r/SKHzyC/1

**Comment by jafacakes2011** [comment]
Looks like you're right! I'm not that well versed in Regex, so my fix was based on some searching around, didn't realise it could be simplified so much!

**Comment by jafacakes2011** [comment]
Just updated the branch to simplify the regex as per the comments 😄

**Comment by christopherpickering** [comment]
sweet, thank you @jafacakes2011!

**Pull request merged**
