### PR TITLE
Replace flake8 and its plugins and isort and pylint with ruff

### PR DESCRIPTION
**Pull request by cclauss**
[Ruff](https://beta.ruff.rs) supports [over 400 lint rules](https://beta.ruff.rs/docs/rules) including flake8, isort, and pylint and is written in Rust for speed.
# Pull Request Checklist

Resolves: #issue-number-here

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by christopherpickering** [comment]
Interesting, thanks for suggesting this, I will check it out!

**Comment by christopherpickering** [comment]
note to self - need to make sure the demo is still working w/ py 3.11.

**Comment by christopherpickering** [comment]
Pyodide is still [using py 3.10](https://github.com/pyodide/pyodide/issues/3534), but there should be no problem building djlint on 3.11 and running on 3.10 as that is how everyone is using it :)

I'm happy to merge this in if you are all set. I don't think we need the `DJ` lint but it is causing no harm. I'm afraid it might start flagging intentionally bad tests at some point.

**Comment by cclauss** [comment]
Ready to merge.  The `DJ` thing will be easy to disable if it gets in our way.

**Comment by christopherpickering** [comment]
Thanks, it should get to master sometime on monday after dep updates.

**Pull request merged**
