### PR TITLE
feat(formatter): Add option to not condense multi-line-tags

### PR DESCRIPTION
**Pull request by timoludwig**
# Pull Request Check List

Resolves: #624

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

## Open questions

I noticed that this feature does work for all block-level tags, but not for inline tags that are not listed in [`break_template_tags`](https://github.com/Riverside-Healthcare/djLint/blob/7c025e30eab67204c20cf7db07572db4261c7792/src/djlint/settings.py#L653) (e.g. `a` or `span`)... 

So the fragment
```
<a href="{% url "myview" %}"
   class="class another-class and-yet-another-one"
   target="_blank"
   rel="noopener noreferrer">linktext</a>
```
is still remains unchanged and is not formatted like this:
```
<a href="{% url "myview" %}"
   class="class another-class and-yet-another-one"
   target="_blank"
   rel="noopener noreferrer">
    linktext
</a>
```

Could I just add them dynamically when the option `--line-break-after-multiline-tag` is given? Or are there weird edge cases like e.g.
```
inline text <a href="{% url "myview" %}"
    class="class another-class and-yet-another-one"
    target="_blank"
    rel="noopener noreferrer">linktext</a> line continues
```
where it's desired to keep this indentation?
In my opinion however, this does not look visually pleasing... I guess I would prefer it if 
1. Either the tag is completely inlined, even if it makes the line longer than the limit:
   ```
   inline text <a href="{% url "myview" %}" class="class another-class and-yet-another-one" target="_blank" rel="noopener noreferrer">linktext</a>line continues
   ```
3. or also puts the tag in its new line, e.g.:
   ```
   inline text
   <a href="{% url "myview" %}"
      class="class another-class and-yet-another-one"
      target="_blank"
      rel="noopener noreferrer">
       linktext
   </a>
   line continues
   ```
   Although I'm, not sure if there are many people that would agree...

What's your opinion on this? Is this a separate topic and should I open a different issue for this (expansion instead of condensation)?

### CODE REVIEW

**Comment by christopherpickering** [comment]
ah forgot about it on the `a` tags. We can't add breaks on space senstive tags. (a, span etc as you found)

this PR looks good tho.

You can probably add `a` tags to your [custom html](https://djlint.com/docs/configuration/#custom-html) list.. which will add them to the break tag list ;) Its not good to add space tho.

**Comment by christopherpickering** [comment]
If it is any consolation to you, the 2.0 branch will do the same style as prettier - breaking, but keeping the > and < with the text.

image

One think we are missing in djlint > if there was white space around your word "linktext" then the tag should be breakable. right now djlint isn't smart enough to figure that out.

**Comment by timoludwig** [comment]
> You can probably add `a` tags to your [custom html](https://djlint.com/docs/configuration/#custom-html) list.. which will add them to the break tag list ;) Its not good to add space tho.

Ah good idea, yes this seems to do what I want. But yeah ok, I agree that a formatter should only make the code pretty and not change the rendered outcome... this is probably also the reason why this is not documented?
Maybe my needs are not compatible with the html spec :sweat_smile: 

> If it is any consolation to you, the 2.0 branch will do the same style as prettier - breaking, but keeping the > and < with the text.

Hmm, to me personally this doesn't look too pleasing either, I'm always using the [bracket-line](https://prettier.io/docs/en/options.html#bracket-line) option, I think I'd even prefer the condensation into the line of the last attribute :see_no_evil: 
Maybe I'll open another feature request once 2.0 is out :joy:

> One think we are missing in djlint > if there was white space around your word "linktext" then the tag should be breakable. right now djlint isn't smart enough to figure that out.

Also sounds like an interesting idea to work on when I have a little time... :+1:

**Comment by christopherpickering** [comment]
in v2 we should have a flag like prettier 😁 

I'm going to merge, thank you very much!

**Pull request merged**
