### PR TITLE
Define first letter before the rules and sort both

### PR DESCRIPTION
**Pull request by cclauss**
Sorting lists makes it easier for users to look up codes, spot missing codes, and challenging to insert duplicate codes.

Sorting lines is easy in vscode... Select lines to be sorted.  Shift-Cmd-P and type `sort` and select `Sort Lines Ascending`.

Preview: https://deploy-preview-391--djlint.netlify.app/docs/linter/#code-patterns

# Pull Request Check List

Resolves: #issue-number-here

- [ ] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by christopherpickering** [comment]
Hmm, it was sorted by the numbers before. Do you find this easier to read?

**Comment by cclauss** [comment]
Yes, I do.

**Comment by christopherpickering** [comment]
I'll update the french and russian pages as well. I'm thinking I will drop those soon as only a handful of russian pages are used, and no french.

... unless you can sort those in vs quickly as well?
/fr/docs/ and /ru/docs/

**Comment by christopherpickering** [comment]
Thanks!

**Pull request merged**
