### PR TITLE
Allowed more than one path at a time

### PR DESCRIPTION
**Pull request by matthiask**
Here's another pull request which adds support for passing several folders at once, e.g. `djlint --reformat app1/ app2/`

This is useful when you have more than one folder at the top level of a repository.

### CODE REVIEW

**Comment by matthiask** [comment]
I don't know where the coverage difference comes from. Strange...

**Comment by christopherpickering** [comment]
Yeah,  odd on the coverage, but it looks like the test for "-" as a src is not showing coverage for that block. I'll check that out, otherwise, nice addition!

**Comment by christopherpickering** [comment]
Ah I see the test ``test_stdin`` is not checking output :/ I will clean that up.

**Comment by christopherpickering** [comment]
Release on djlint==0.4.1
Thanks!

**Comment by matthiask** [comment]
Thanks! :)

**Pull request merged**
