### PR TITLE
Python based rules

### PR DESCRIPTION
**Pull request by Alabate**
# Pull Request Check List

Resolves: #618

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

Solution suggested: A simple `python_module` attribute in `rules.yml` that will be imported. This module must contain a function `run()` that will be executed on every files.

Notes:
- I move H025 to another file to avoid having code specific to a rule in the main `lint.py`
- I did the french documentation, but I don't speak russian, so I cannot do this one.
- In the documentation I re-ordered stuff, because I think that custom rules are an advanced usage, and the rule list is more important to most users.

### CODE REVIEW

**Comment by christopherpickering** [comment]
do you think you can set it up in the docs to allow extra stuff to be passed in? **args and *kwargs? I'd like to rewrite the linter to use a tokenized html at some point, and if people are already allowing other args in there functions it is less likly to break? :)

**Comment by Alabate** [comment]
Good idea, done!

**Comment by christopherpickering** [comment]
Thank you @Alabate !

**Pull request merged**
