### PR TITLE
Make the repo a pre-commit hook.

### PR DESCRIPTION
**Pull request by Rjevski**
# Pull Request Check List

This makes the repo a pre-commit hook and provides some predefined hooks for common frameworks.

Resolves: #issue-number-here

- [ ] Added **tests** for changed code. - no code was changed
- [x] Updated **documentation** for changed code.

### CODE REVIEW

**Review by christopherpickering — COMMENTED** [review]
Thanks! I was going to suggest changing the django file extension, but I guess it can be overridden when used.
What about docs an optional arg for --reformat?

**Comment by Rjevski** [comment]
Any chance you can create a minor release tag? Pre-commit config files ideally need to reference a tag.

**Comment by christopherpickering** [comment]
Yes, sorry I didn't of that 😀

**Comment by christopherpickering** [comment]
https://github.com/Riverside-Healthcare/djLint/releases/tag/0.5.9a, it works ok for you?

**Comment by Rjevski** [comment]
I don't have a chance to test it now but provided the tag is on (or after) the commit of this PR I don't see why it shouldn't work!

**Pull request merged**
