### PR TITLE
adds missing shebang in node binary

### PR DESCRIPTION
**Pull request by ValJed**
# What this PR for
I noticed syntax error when trying to run `djlint` binary installed with `npm`.
Just looked at the code and found that it was a node.js file used as a binary but without a shebang, so my system was not able to run it.

I tested locally, it fixes my issue.

Let me know if it's good for you!

# Pull Request Check List

Resolves: no issue

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by christopherpickering** [comment]
Thanks for this! I'll test it out on a few OS's. I'm not too familiar w/ the node shebangs, but it sounds like the one you have is supposed to be universal.

**Comment by christopherpickering** [comment]
What os are you on by the way? I'm wondering what I should change in my GitHub test action to catch the failure?

**Comment by ValJed** [comment]
> What os are you on by the way? I'm wondering what I should change in my GitHub test action to catch the failure?

Hello, sorry for the delay, I'm currently on Ubuntu 20.04.4 (Focal).

Thanks.

**Pull request merged**
